CREATE TYPE "property_status" AS ENUM (
  'active',
  'unavailable'
);

CREATE TABLE "groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invite_code" varchar UNIQUE,
  "name" varchar,
  "adults" int,
  "teens" int DEFAULT 0,
  "child" int DEFAULT 0,
  "pets" int DEFAULT 0,
  "date_range_start" date,
  "date_range_end" date,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "destinations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int,
  "location_name" varchar
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int,
  "nickname" varchar,
  "joined_at" timestamp DEFAULT (now()),
  "avatar" varchar
);

CREATE TABLE "user_filters" (
  "user_id" int PRIMARY KEY,
  "min_price" int,
  "max_price" int,
  "min_bedrooms" int,
  "min_beds" int,
  "min_bathrooms" int,
  "property_type" varchar,
  "updated_at" timestamp
);

CREATE TABLE "filter_ameneties" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "amenities_id" int
);

CREATE TABLE "filter_request" (
  "user_id" int PRIMARY KEY,
  "destination_id" int,
  "pages_fetched" int,
  "pages_total" int
);

CREATE TABLE "properties" (
  "airbnb_id" varchar PRIMARY KEY,
  "title" varchar,
  "price_per_night" int,
  "bnb_rating" decimal,
  "bnb_review_count" int,
  "main_image_url" varchar,
  "description" text,
  "min_bedrooms" int,
  "min_beds" int,
  "min_bathrooms" int,
  "property_type" varchar
);

CREATE TABLE "propertie_ameneties" (
  "airbnb_id" int,
  "ameneties_id" int
);

CREATE TABLE "propertie_images" (
  "propertie_id" int,
  "image_url" varchar
);

CREATE TABLE "group_candidates" (
  "group_id" int,
  "property_id" int,
  "added_at" timestamp,
  PRIMARY KEY ("group_id", "property_id")
);

CREATE TABLE "votes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "property_id" int,
  "rating" int,
  "created_at" timestamp,
  "reason" varchar
);

CREATE INDEX ON "properties" ("airbnb_id");

CREATE UNIQUE INDEX ON "votes" ("user_id", "property_id");

ALTER TABLE "destinations" ADD FOREIGN KEY ("id") REFERENCES "filter_request" ("destination_id");

ALTER TABLE "destinations" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "user_filters" ("user_id");

ALTER TABLE "filter_ameneties" ADD FOREIGN KEY ("user_id") REFERENCES "user_filters" ("user_id");

ALTER TABLE "propertie_images" ADD FOREIGN KEY ("propertie_id") REFERENCES "properties" ("airbnb_id");

ALTER TABLE "group_candidates" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "group_candidates" ADD FOREIGN KEY ("property_id") REFERENCES "properties" ("airbnb_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "votes" ADD FOREIGN KEY ("property_id") REFERENCES "properties" ("airbnb_id");

ALTER TABLE "propertie_ameneties" ADD FOREIGN KEY ("airbnb_id") REFERENCES "properties" ("airbnb_id");

CREATE TABLE "filter_request_users" (
  "filter_request_user_id" int,
  "users_id" int,
  PRIMARY KEY ("filter_request_user_id", "users_id")
);

ALTER TABLE "filter_request_users" ADD FOREIGN KEY ("filter_request_user_id") REFERENCES "filter_request" ("user_id");

ALTER TABLE "filter_request_users" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

